#Listener Configuration
listen 1883

#WebSocket Listener Configuration
#listener 9001
#protocol websockets


#Authentication Configuration
allow_anonymous true

#Data persistence Configuration
persistence true
persistence/location /mosquitto/data/


#logging Configuration
log_dest stdout
log_dest fiele /mosquitto/log/mosquitto.log

#log message types
log_type error
log_type warning    
log_type notice
log_type information


#Connectiion logging
connection_messages true

#Message logging
log_type all

#Quality of Service
max_qos 2

#Message Retention
max_retained_messages 1000

#Maximum connections    
max_connections -1

#Maximum size limit for incoming messages

message_size_limit 0
# 0 limit

#Keep alive
keepalive_interval 66535